## *** 下方各项配置，确保输入配置格式正确，配置信息首尾注意不要留有空格等，当前版本暂不支持trimspace ***
application:
  name: evm-scan
chain:
  # evm链结点地址
  url: "https://rpc.zkfair.io"
  # 请求超时时间，如无特殊必要，默认60即可，单位：秒
  timeout: 60
  # 读取每个块之间延迟时间，根据网络情况调整，单位毫秒，一定范围内，越小速度越快
  blockDelay: 70
  # 块线程池大小，根据网络情况调整，一定范围内，越大速度越快
  blockThreadSize: 500
  # 缓存交易笔数，每次缓存指定长度后，再提交
  txCacheSize: 100
database:
  # 目前仅支持mysql
  driver: mysql
  # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  source: root:xxx@tcp(127.0.0.1:8990)/app?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  # 最大连接时间，按官方建议，不建议超过500秒，参考：https://github.com/go-sql-driver/mysql
  connMaxLifetime: 180
  # 最大连接数
  maxOpenConns: 50
  # 最大空闲连接数，按官方建议，和maxOpenConns设置一样大小，参考：https://github.com/go-sql-driver/mysql
  maxIdleConns: 50
  # 最大空闲连接时间（单位秒）
  connMaxIdleTime: 180
logger:
  # 日志存放路径
  path: files/logs
  # 日志输出，file：文件，default：命令行，其他：命令行
  stdout: '' #控制台日志，启用后，不输出到文件
  # 日志等级, trace, debug, info, warn, error, fatal
  level: trace
  type: default
